### PR TITLE
Docker Hardening

### PR DESCRIPTION
**Pull request by jason-fox**
This PR fixes several issues raised by [docker/docker-bench-security](https://github.com/docker/docker-bench-security)

- Add missing `HEALTHCHECK` - currently just a ping to `/iota/about`, but could be expanded
- Add standard metadata build `LABEL` (see [opencontainers.org](https://github.com/opencontainers/opencontainers.org))
- Remove **deprecated** `MAINTAINER` - replace with `LABEL`
- Create two-stage build process  using a **Distroless** build:

     -    Remove [disto](https://medium.com/@dwdraju/distroless-is-for-security-if-not-for-size-6eac789f695f)
     -    Run as anonymous user
     -    Set `NODE_ENV` to development/production

### CODE REVIEW

**Comment by jason-fox** [comment]
The documentation failure is fixed by PR https://github.com/telefonicaid/sigfox-iotagent/pull/87

**Comment by jason-fox** [comment]
To maintain docker secrets support, this PR should be processed after https://github.com/telefonicaid/iotagent-node-lib/pull/885

**Comment by jason-fox** [comment]
@fgalan @AlvaroVega - This PR is ready for review

**Review by AlvaroVega — APPROVED** [review]
LGTM

**Review by fgalan — APPROVED** [review]
LGTM

We are conducting right now some test with final result of this approach in IOTA-JSON. Once we confirm it's ok, we will merge this PR.

**Comment by fgalan** [comment]
After some final fixes (PR https://github.com/telefonicaid/iotagent-node-lib/pull/915) CI for IOTA-JSON worked, so we are merging now the rest of pending PRs related this.

**Pull request merged**
