### PR TITLE
Feature/ngsi ld #82

### PR DESCRIPTION
**Pull request by vraybaud**

### CODE REVIEW

**Comment by fgalan** [comment]
Thanks for your contribution!

Note that some files have conflicts. They need to be solved.

Moreover, this PR seems to content same as in PR #83. I understand the ideas is to upgrade this one with master once PR #83 gets merged, isn't it?

**Comment by fgalan** [comment]
> Note that some files have conflicts. They need to be solved.

Probably that should wait until PR #83 gets merged and this PR upgraded with master.

**Comment by bobeal** [comment]
You can close this PR, I'm preparing a new clean one (but dependent on the final decision for https://github.com/telefonicaid/iotagent-node-lib/pull/888)

**Comment by fgalan** [comment]
Ok. Closing.

**Pull request closed without merging**
