### PR TITLE
 [TMP] Test NGSIv1 removal

### PR DESCRIPTION
**Pull request by fgalan**
By the moment, this PR is just for testing how this component unit tests behave when using jason-fox:feature/ngsi-v1 branch in the IOTA Lib.

### CODE REVIEW

**Comment by fgalan** [comment]
Just to check if master branch was already broken, I have just launch GithActions on master. Result is https://github.com/telefonicaid/sigfox-iotagent/runs/3068561488, showing everyhing ok.

So I understand the fails in this PR are due to the usage of  jason-fox:feature/ngsi-v1 branch in the IOTA Lib.

**Comment by fgalan** [comment]
Looking for isCurrentNgsi() ocurrences in this repository (as we have done in other IOTAs) it seems this time we have none

https://github.com/telefonicaid/sigfox-iotagent/search?q=isCurrentNgsi

**Comment by jason-fox** [comment]
Tests are fixed in https://github.com/telefonicaid/sigfox-iotagent/pull/111 - should be merged into this PR for testing.

**Comment by fgalan** [comment]
After merging PR https://github.com/telefonicaid/iotagent-node-lib/pull/995 this PR is no longer needed. Closing.

**Pull request closed without merging**
