### PR TITLE
ADD google_analytics to mkdocs.yml

### PR DESCRIPTION
**Pull request by fgalan**
Please @jason-fox review.

As far as I understand this concludes the onbording of IOTA Sigfox as GE Incubated work.

### CODE REVIEW

**Comment by flopezag** [comment]
Hi Fermin, just to finish the configuration of the Google Analytics you have to provide access (at least read grant) to the user fiware.eu@gmail.com

**Comment by fgalan** [comment]
> Hi Fermin, just to finish the configuration of the Google Analytics you have to provide access (at least read grant) to the user [fiware.eu@gmail.com](mailto:fiware.eu@gmail.com)

Read and collaborate grant has been provided. Could you confirm @flopezag pls? Thanks!

**Comment by flopezag** [comment]
@fgalan, Could you provide permissions for 
Edit, Collaborate, Read & Analyse, Manage Users?

**Comment by fgalan** [comment]
Collaborate and Read & Analyse are already granted. Why do you need Edit and Manage User permissions?

**Comment by fgalan** [comment]
@jason-fox @flopezag is this PR ok to be merged, please? Thx!

**Comment by flopezag** [comment]
I am not sure if the issues had been resolved but we can merge the PR and see if there is something missing.

**Review by mapedraza — APPROVED** [review]
LGTM

**Pull request merged**
